DROP DATABASE IF EXISTS hibernate;
CREATE DATABASE hibernate;
USE hibernate;

CREATE TABLE id_card
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	card_no VARCHAR(32) NOT NULL UNIQUE ,
	PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8;

CREATE TABLE person2
(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	card_id INTEGER UNIQUE ,
	PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8;

ALTER TABLE person2 ADD FOREIGN KEY card_id_idxfk (card_id) REFERENCES id_card (id);
